import { createServerFn } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { z } from "zod";

const subscribeSchema = z.object({
  email: z.string().trim().min(3).max(320).email(),
  source: z.string().max(100).optional(),
});

function confirmationEmailHtml(confirmUrl: string): string {
  return `
    <div style="font-family: Georgia, serif; max-width: 480px; margin: 0 auto; padding: 24px; color: #1a1a1a;">
      <p style="font-size: 11px; letter-spacing: 0.2em; text-transform: uppercase; color: #8a7358;">The Last Mukwasu</p>
      <h1 style="font-size: 22px; margin: 12px 0;">Confirm your subscription</h1>
      <p style="font-size: 15px; line-height: 1.6;">One step left — click below to start receiving letters from the lounge.</p>
      <p style="margin: 28px 0;">
        <a href="${confirmUrl}" style="background: #b08d57; color: #1a1a1a; padding: 12px 24px; text-decoration: none; font-weight: bold; display: inline-block;">Confirm subscription</a>
      </p>
      <p style="font-size: 12px; color: #777;">If the button doesn't work, paste this into your browser:<br>${confirmUrl}</p>
      <p style="font-size: 12px; color: #999; margin-top: 32px;">Didn't sign up? Ignore this email — you won't be subscribed unless you click the link above.</p>
    </div>
  `;
}

/**
 * Records a newsletter signup and sends a confirmation email via Resend.
 * Runs server-side so the confirm token is generated by the database
 * (never trusted from the client) and RESEND_API_KEY never reaches the
 * browser bundle.
 */
export const subscribeToNewsletter = createServerFn({ method: "POST" })
  .validator(subscribeSchema)
  .handler(async ({ data }) => {
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const email = data.email.toLowerCase();

    const { data: row, error } = await supabaseAdmin
      .from("newsletter_subscribers")
      .insert({ email, source: data.source ?? null })
      .select("confirm_token")
      .single();

    if (error) {
      // 23505 = unique_violation — already on the list. Don't reveal
      // confirmed/unconfirmed state to the caller, and don't re-send.
      if (error.code === "23505") {
        return { status: "already_subscribed" as const };
      }
      throw new Error(error.message);
    }

    const request = getRequest();
    const origin = request ? new URL(request.url).origin : "";
    const confirmUrl = `${origin}/newsletter/confirm?token=${row!.confirm_token}`;

    try {
      const { sendEmail } = await import("@/lib/resend.server");
      await sendEmail({
        to: email,
        subject: "Confirm your subscription — The Last Mukwasu",
        html: confirmationEmailHtml(confirmUrl),
        text: `Confirm your subscription to The Last Mukwasu: ${confirmUrl}\n\nDidn't sign up? Ignore this email.`,
      });
    } catch (sendErr) {
      // The row is saved either way; let the caller know the email itself
      // didn't go out so the UI can say something more honest than "check
      // your inbox" when it won't arrive.
      console.error("[newsletter] confirmation email failed to send:", sendErr);
      return { status: "saved_email_failed" as const };
    }

    return { status: "confirmation_sent" as const };
  });
