/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as DiariesRouteImport } from './routes/diaries'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShowRouteImport } from './routes/show'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as AuthenticatedAccountRouteRouteImport } from './routes/_authenticated/account/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as CollectionDearTodayRouteImport } from './routes/collection_.dear-today'
import { Route as DiariesSlugRouteImport } from './routes/diaries_.$slug'
import { Route as StoriesSlugRouteImport } from './routes/stories_.$slug'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account/index'
import { Route as AuthenticatedAccountBookmarksRouteImport } from './routes/_authenticated/account/bookmarks'
import { Route as AuthenticatedAccountCommentsRouteImport } from './routes/_authenticated/account/comments'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAboutRouteImport } from './routes/_authenticated/admin/about'
import { Route as AuthenticatedAdminCollectionRouteImport } from './routes/_authenticated/admin/collection'
import { Route as AuthenticatedAdminCommentsRouteImport } from './routes/_authenticated/admin/comments'
import { Route as AuthenticatedAdminDearTodayRouteImport } from './routes/_authenticated/admin/dear-today'
import { Route as AuthenticatedAdminDiaryRouteImport } from './routes/_authenticated/admin/diary'
import { Route as AuthenticatedAdminGalleryRouteImport } from './routes/_authenticated/admin/gallery'
import { Route as AuthenticatedAdminHeroRouteImport } from './routes/_authenticated/admin/hero'
import { Route as AuthenticatedAdminNewsletterRouteImport } from './routes/_authenticated/admin/newsletter'
import { Route as AuthenticatedAdminShopRouteImport } from './routes/_authenticated/admin/shop'
import { Route as AuthenticatedAdminShowsRouteImport } from './routes/_authenticated/admin/shows'
import { Route as AuthenticatedAdminStoriesRouteImport } from './routes/_authenticated/admin/stories'
import { Route as AuthenticatedAdminTaxonomyRouteImport } from './routes/_authenticated/admin/taxonomy'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as CollectionDearTodaySlugRouteImport } from './routes/collection_.dear-today_.$slug'
import { Route as CollectionSeriesSlugRouteImport } from './routes/collection_.series.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const DiariesRoute = DiariesRouteImport.update({
  id: '/diaries',
  path: '/diaries',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowRoute = ShowRouteImport.update({
  id: '/show',
  path: '/show',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRouteRoute =
  AuthenticatedAccountRouteRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CollectionDearTodayRoute = CollectionDearTodayRouteImport.update({
  id: '/collection_/dear-today',
  path: '/collection/dear-today',
  getParentRoute: () => rootRouteImport,
} as any)
const DiariesSlugRoute = DiariesSlugRouteImport.update({
  id: '/diaries_/$slug',
  path: '/diaries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/stories_/$slug',
  path: '/stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)
const AuthenticatedAccountBookmarksRoute =
  AuthenticatedAccountBookmarksRouteImport.update({
    id: '/bookmarks',
    path: '/bookmarks',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)
const AuthenticatedAccountCommentsRoute =
  AuthenticatedAccountCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAboutRoute = AuthenticatedAdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCollectionRoute =
  AuthenticatedAdminCollectionRouteImport.update({
    id: '/collection',
    path: '/collection',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCommentsRoute =
  AuthenticatedAdminCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDearTodayRoute =
  AuthenticatedAdminDearTodayRouteImport.update({
    id: '/dear-today',
    path: '/dear-today',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDiaryRoute = AuthenticatedAdminDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminGalleryRoute =
  AuthenticatedAdminGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminHeroRoute = AuthenticatedAdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminNewsletterRoute =
  AuthenticatedAdminNewsletterRouteImport.update({
    id: '/newsletter',
    path: '/newsletter',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminShopRoute = AuthenticatedAdminShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminShowsRoute = AuthenticatedAdminShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminStoriesRoute =
  AuthenticatedAdminStoriesRouteImport.update({
    id: '/stories',
    path: '/stories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTaxonomyRoute =
  AuthenticatedAdminTaxonomyRouteImport.update({
    id: '/taxonomy',
    path: '/taxonomy',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const CollectionDearTodaySlugRoute = CollectionDearTodaySlugRouteImport.update({
  id: '/collection_/dear-today_/$slug',
  path: '/collection/dear-today/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionSeriesSlugRoute = CollectionSeriesSlugRouteImport.update({
  id: '/collection_/series/$slug',
  path: '/collection/series/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/collection': typeof CollectionRoute
  '/diaries': typeof DiariesRoute
  '/gallery': typeof GalleryRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/show': typeof ShowRoute
  '/stories': typeof StoriesRoute
  '/account': typeof AuthenticatedAccountRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/collection/dear-today': typeof CollectionDearTodayRoute
  '/diaries/$slug': typeof DiariesSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/account/bookmarks': typeof AuthenticatedAccountBookmarksRoute
  '/account/comments': typeof AuthenticatedAccountCommentsRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/collection': typeof AuthenticatedAdminCollectionRoute
  '/admin/comments': typeof AuthenticatedAdminCommentsRoute
  '/admin/dear-today': typeof AuthenticatedAdminDearTodayRoute
  '/admin/diary': typeof AuthenticatedAdminDiaryRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/shop': typeof AuthenticatedAdminShopRoute
  '/admin/shows': typeof AuthenticatedAdminShowsRoute
  '/admin/stories': typeof AuthenticatedAdminStoriesRoute
  '/admin/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/collection/dear-today/$slug': typeof CollectionDearTodaySlugRoute
  '/collection/series/$slug': typeof CollectionSeriesSlugRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/collection': typeof CollectionRoute
  '/diaries': typeof DiariesRoute
  '/gallery': typeof GalleryRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/show': typeof ShowRoute
  '/stories': typeof StoriesRoute
  '/collection/dear-today': typeof CollectionDearTodayRoute
  '/diaries/$slug': typeof DiariesSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/account/bookmarks': typeof AuthenticatedAccountBookmarksRoute
  '/account/comments': typeof AuthenticatedAccountCommentsRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/collection': typeof AuthenticatedAdminCollectionRoute
  '/admin/comments': typeof AuthenticatedAdminCommentsRoute
  '/admin/dear-today': typeof AuthenticatedAdminDearTodayRoute
  '/admin/diary': typeof AuthenticatedAdminDiaryRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/admin/shop': typeof AuthenticatedAdminShopRoute
  '/admin/shows': typeof AuthenticatedAdminShowsRoute
  '/admin/stories': typeof AuthenticatedAdminStoriesRoute
  '/admin/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/collection/dear-today/$slug': typeof CollectionDearTodaySlugRoute
  '/collection/series/$slug': typeof CollectionSeriesSlugRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/collection': typeof CollectionRoute
  '/diaries': typeof DiariesRoute
  '/gallery': typeof GalleryRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/show': typeof ShowRoute
  '/stories': typeof StoriesRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/collection_/dear-today': typeof CollectionDearTodayRoute
  '/diaries_/$slug': typeof DiariesSlugRoute
  '/stories_/$slug': typeof StoriesSlugRoute
  '/_authenticated/account/bookmarks': typeof AuthenticatedAccountBookmarksRoute
  '/_authenticated/account/comments': typeof AuthenticatedAccountCommentsRoute
  '/_authenticated/admin/about': typeof AuthenticatedAdminAboutRoute
  '/_authenticated/admin/collection': typeof AuthenticatedAdminCollectionRoute
  '/_authenticated/admin/comments': typeof AuthenticatedAdminCommentsRoute
  '/_authenticated/admin/dear-today': typeof AuthenticatedAdminDearTodayRoute
  '/_authenticated/admin/diary': typeof AuthenticatedAdminDiaryRoute
  '/_authenticated/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/_authenticated/admin/hero': typeof AuthenticatedAdminHeroRoute
  '/_authenticated/admin/newsletter': typeof AuthenticatedAdminNewsletterRoute
  '/_authenticated/admin/shop': typeof AuthenticatedAdminShopRoute
  '/_authenticated/admin/shows': typeof AuthenticatedAdminShowsRoute
  '/_authenticated/admin/stories': typeof AuthenticatedAdminStoriesRoute
  '/_authenticated/admin/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/collection_/dear-today_/$slug': typeof CollectionDearTodaySlugRoute
  '/collection_/series/$slug': typeof CollectionSeriesSlugRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/collection'
    | '/diaries'
    | '/gallery'
    | '/settings'
    | '/shop'
    | '/show'
    | '/stories'
    | '/account'
    | '/admin'
    | '/collection/dear-today'
    | '/diaries/$slug'
    | '/stories/$slug'
    | '/account/bookmarks'
    | '/account/comments'
    | '/admin/about'
    | '/admin/collection'
    | '/admin/comments'
    | '/admin/dear-today'
    | '/admin/diary'
    | '/admin/gallery'
    | '/admin/hero'
    | '/admin/newsletter'
    | '/admin/shop'
    | '/admin/shows'
    | '/admin/stories'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/collection/dear-today/$slug'
    | '/collection/series/$slug'
    | '/account/'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/collection'
    | '/diaries'
    | '/gallery'
    | '/settings'
    | '/shop'
    | '/show'
    | '/stories'
    | '/collection/dear-today'
    | '/diaries/$slug'
    | '/stories/$slug'
    | '/account/bookmarks'
    | '/account/comments'
    | '/admin/about'
    | '/admin/collection'
    | '/admin/comments'
    | '/admin/dear-today'
    | '/admin/diary'
    | '/admin/gallery'
    | '/admin/hero'
    | '/admin/newsletter'
    | '/admin/shop'
    | '/admin/shows'
    | '/admin/stories'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/collection/dear-today/$slug'
    | '/collection/series/$slug'
    | '/account'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/collection'
    | '/diaries'
    | '/gallery'
    | '/settings'
    | '/shop'
    | '/show'
    | '/stories'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/collection_/dear-today'
    | '/diaries_/$slug'
    | '/stories_/$slug'
    | '/_authenticated/account/bookmarks'
    | '/_authenticated/account/comments'
    | '/_authenticated/admin/about'
    | '/_authenticated/admin/collection'
    | '/_authenticated/admin/comments'
    | '/_authenticated/admin/dear-today'
    | '/_authenticated/admin/diary'
    | '/_authenticated/admin/gallery'
    | '/_authenticated/admin/hero'
    | '/_authenticated/admin/newsletter'
    | '/_authenticated/admin/shop'
    | '/_authenticated/admin/shows'
    | '/_authenticated/admin/stories'
    | '/_authenticated/admin/taxonomy'
    | '/_authenticated/admin/users'
    | '/collection_/dear-today_/$slug'
    | '/collection_/series/$slug'
    | '/_authenticated/account/'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CollectionRoute: typeof CollectionRoute
  DiariesRoute: typeof DiariesRoute
  GalleryRoute: typeof GalleryRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  ShowRoute: typeof ShowRoute
  StoriesRoute: typeof StoriesRoute
  CollectionDearTodayRoute: typeof CollectionDearTodayRoute
  DiariesSlugRoute: typeof DiariesSlugRoute
  StoriesSlugRoute: typeof StoriesSlugRoute
  CollectionDearTodaySlugRoute: typeof CollectionDearTodaySlugRoute
  CollectionSeriesSlugRoute: typeof CollectionSeriesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diaries': {
      id: '/diaries'
      path: '/diaries'
      fullPath: '/diaries'
      preLoaderRoute: typeof DiariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/show': {
      id: '/show'
      path: '/show'
      fullPath: '/show'
      preLoaderRoute: typeof ShowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/collection_/dear-today': {
      id: '/collection_/dear-today'
      path: '/collection/dear-today'
      fullPath: '/collection/dear-today'
      preLoaderRoute: typeof CollectionDearTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diaries_/$slug': {
      id: '/diaries_/$slug'
      path: '/diaries/$slug'
      fullPath: '/diaries/$slug'
      preLoaderRoute: typeof DiariesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories_/$slug': {
      id: '/stories_/$slug'
      path: '/stories/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
    '/_authenticated/account/bookmarks': {
      id: '/_authenticated/account/bookmarks'
      path: '/bookmarks'
      fullPath: '/account/bookmarks'
      preLoaderRoute: typeof AuthenticatedAccountBookmarksRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
    '/_authenticated/account/comments': {
      id: '/_authenticated/account/comments'
      path: '/comments'
      fullPath: '/account/comments'
      preLoaderRoute: typeof AuthenticatedAccountCommentsRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/about': {
      id: '/_authenticated/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AuthenticatedAdminAboutRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/collection': {
      id: '/_authenticated/admin/collection'
      path: '/collection'
      fullPath: '/admin/collection'
      preLoaderRoute: typeof AuthenticatedAdminCollectionRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/comments': {
      id: '/_authenticated/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AuthenticatedAdminCommentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dear-today': {
      id: '/_authenticated/admin/dear-today'
      path: '/dear-today'
      fullPath: '/admin/dear-today'
      preLoaderRoute: typeof AuthenticatedAdminDearTodayRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/diary': {
      id: '/_authenticated/admin/diary'
      path: '/diary'
      fullPath: '/admin/diary'
      preLoaderRoute: typeof AuthenticatedAdminDiaryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/gallery': {
      id: '/_authenticated/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AuthenticatedAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/hero': {
      id: '/_authenticated/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AuthenticatedAdminHeroRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/newsletter': {
      id: '/_authenticated/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AuthenticatedAdminNewsletterRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/shop': {
      id: '/_authenticated/admin/shop'
      path: '/shop'
      fullPath: '/admin/shop'
      preLoaderRoute: typeof AuthenticatedAdminShopRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/shows': {
      id: '/_authenticated/admin/shows'
      path: '/shows'
      fullPath: '/admin/shows'
      preLoaderRoute: typeof AuthenticatedAdminShowsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/stories': {
      id: '/_authenticated/admin/stories'
      path: '/stories'
      fullPath: '/admin/stories'
      preLoaderRoute: typeof AuthenticatedAdminStoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/taxonomy': {
      id: '/_authenticated/admin/taxonomy'
      path: '/taxonomy'
      fullPath: '/admin/taxonomy'
      preLoaderRoute: typeof AuthenticatedAdminTaxonomyRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/collection_/dear-today_/$slug': {
      id: '/collection_/dear-today_/$slug'
      path: '/collection/dear-today/$slug'
      fullPath: '/collection/dear-today/$slug'
      preLoaderRoute: typeof CollectionDearTodaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection_/series/$slug': {
      id: '/collection_/series/$slug'
      path: '/collection/series/$slug'
      fullPath: '/collection/series/$slug'
      preLoaderRoute: typeof CollectionSeriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAccountRouteRouteChildren {
  AuthenticatedAccountBookmarksRoute: typeof AuthenticatedAccountBookmarksRoute
  AuthenticatedAccountCommentsRoute: typeof AuthenticatedAccountCommentsRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedAccountRouteRouteChildren: AuthenticatedAccountRouteRouteChildren =
  {
    AuthenticatedAccountBookmarksRoute: AuthenticatedAccountBookmarksRoute,
    AuthenticatedAccountCommentsRoute: AuthenticatedAccountCommentsRoute,
    AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  }

const AuthenticatedAccountRouteRouteWithChildren =
  AuthenticatedAccountRouteRoute._addFileChildren(
    AuthenticatedAccountRouteRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAboutRoute: typeof AuthenticatedAdminAboutRoute
  AuthenticatedAdminCollectionRoute: typeof AuthenticatedAdminCollectionRoute
  AuthenticatedAdminCommentsRoute: typeof AuthenticatedAdminCommentsRoute
  AuthenticatedAdminDearTodayRoute: typeof AuthenticatedAdminDearTodayRoute
  AuthenticatedAdminDiaryRoute: typeof AuthenticatedAdminDiaryRoute
  AuthenticatedAdminGalleryRoute: typeof AuthenticatedAdminGalleryRoute
  AuthenticatedAdminHeroRoute: typeof AuthenticatedAdminHeroRoute
  AuthenticatedAdminNewsletterRoute: typeof AuthenticatedAdminNewsletterRoute
  AuthenticatedAdminShopRoute: typeof AuthenticatedAdminShopRoute
  AuthenticatedAdminShowsRoute: typeof AuthenticatedAdminShowsRoute
  AuthenticatedAdminStoriesRoute: typeof AuthenticatedAdminStoriesRoute
  AuthenticatedAdminTaxonomyRoute: typeof AuthenticatedAdminTaxonomyRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAboutRoute: AuthenticatedAdminAboutRoute,
    AuthenticatedAdminCollectionRoute: AuthenticatedAdminCollectionRoute,
    AuthenticatedAdminCommentsRoute: AuthenticatedAdminCommentsRoute,
    AuthenticatedAdminDearTodayRoute: AuthenticatedAdminDearTodayRoute,
    AuthenticatedAdminDiaryRoute: AuthenticatedAdminDiaryRoute,
    AuthenticatedAdminGalleryRoute: AuthenticatedAdminGalleryRoute,
    AuthenticatedAdminHeroRoute: AuthenticatedAdminHeroRoute,
    AuthenticatedAdminNewsletterRoute: AuthenticatedAdminNewsletterRoute,
    AuthenticatedAdminShopRoute: AuthenticatedAdminShopRoute,
    AuthenticatedAdminShowsRoute: AuthenticatedAdminShowsRoute,
    AuthenticatedAdminStoriesRoute: AuthenticatedAdminStoriesRoute,
    AuthenticatedAdminTaxonomyRoute: AuthenticatedAdminTaxonomyRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRouteRoute: typeof AuthenticatedAccountRouteRouteWithChildren
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRouteRoute: AuthenticatedAccountRouteRouteWithChildren,
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CollectionRoute: CollectionRoute,
  DiariesRoute: DiariesRoute,
  GalleryRoute: GalleryRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  ShowRoute: ShowRoute,
  StoriesRoute: StoriesRoute,
  CollectionDearTodayRoute: CollectionDearTodayRoute,
  DiariesSlugRoute: DiariesSlugRoute,
  StoriesSlugRoute: StoriesSlugRoute,
  CollectionDearTodaySlugRoute: CollectionDearTodaySlugRoute,
  CollectionSeriesSlugRoute: CollectionSeriesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
