/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DiariesRouteImport } from './routes/diaries'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'
import { Route as DiariesSlugRouteImport } from './routes/diaries.$slug'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminStoriesRouteImport } from './routes/_authenticated/admin/stories'
import { Route as AuthenticatedAdminShopRouteImport } from './routes/_authenticated/admin/shop'
import { Route as AuthenticatedAdminGalleryRouteImport } from './routes/_authenticated/admin/gallery'
import { Route as AuthenticatedAdminDiaryRouteImport } from './routes/_authenticated/admin/diary'
import { Route as AuthenticatedAdminCollectionRouteImport } from './routes/_authenticated/admin/collection'
import { Route as AuthenticatedAdminAboutRouteImport } from './routes/_authenticated/admin/about'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DiariesRoute = DiariesRouteImport.update({
  id: '/diaries',
  path: '/diaries',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StoriesRoute,
} as any)
const DiariesSlugRoute = DiariesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DiariesRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminStoriesRoute =
  AuthenticatedAdminStoriesRouteImport.update({
    id: '/stories',
    path: '/stories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminShopRoute = AuthenticatedAdminShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminGalleryRoute =
  AuthenticatedAdminGalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDiaryRoute = AuthenticatedAdminDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCollectionRoute =
  AuthenticatedAdminCollectionRouteImport.update({
    id: '/collection',
    path: '/collection',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAboutRoute = AuthenticatedAdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/collection': typeof CollectionRoute
  '/diaries': typeof DiariesRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/shop': typeof ShopRoute
  '/stories': typeof StoriesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/diaries/$slug': typeof DiariesSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/collection': typeof AuthenticatedAdminCollectionRoute
  '/admin/diary': typeof AuthenticatedAdminDiaryRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/shop': typeof AuthenticatedAdminShopRoute
  '/admin/stories': typeof AuthenticatedAdminStoriesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/collection': typeof CollectionRoute
  '/diaries': typeof DiariesRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/shop': typeof ShopRoute
  '/stories': typeof StoriesRouteWithChildren
  '/diaries/$slug': typeof DiariesSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/admin/about': typeof AuthenticatedAdminAboutRoute
  '/admin/collection': typeof AuthenticatedAdminCollectionRoute
  '/admin/diary': typeof AuthenticatedAdminDiaryRoute
  '/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/admin/shop': typeof AuthenticatedAdminShopRoute
  '/admin/stories': typeof AuthenticatedAdminStoriesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/collection': typeof CollectionRoute
  '/diaries': typeof DiariesRouteWithChildren
  '/gallery': typeof GalleryRoute
  '/shop': typeof ShopRoute
  '/stories': typeof StoriesRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/diaries/$slug': typeof DiariesSlugRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/_authenticated/admin/about': typeof AuthenticatedAdminAboutRoute
  '/_authenticated/admin/collection': typeof AuthenticatedAdminCollectionRoute
  '/_authenticated/admin/diary': typeof AuthenticatedAdminDiaryRoute
  '/_authenticated/admin/gallery': typeof AuthenticatedAdminGalleryRoute
  '/_authenticated/admin/shop': typeof AuthenticatedAdminShopRoute
  '/_authenticated/admin/stories': typeof AuthenticatedAdminStoriesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/collection'
    | '/diaries'
    | '/gallery'
    | '/shop'
    | '/stories'
    | '/admin'
    | '/diaries/$slug'
    | '/stories/$slug'
    | '/admin/about'
    | '/admin/collection'
    | '/admin/diary'
    | '/admin/gallery'
    | '/admin/shop'
    | '/admin/stories'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/collection'
    | '/diaries'
    | '/gallery'
    | '/shop'
    | '/stories'
    | '/diaries/$slug'
    | '/stories/$slug'
    | '/admin/about'
    | '/admin/collection'
    | '/admin/diary'
    | '/admin/gallery'
    | '/admin/shop'
    | '/admin/stories'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/collection'
    | '/diaries'
    | '/gallery'
    | '/shop'
    | '/stories'
    | '/_authenticated/admin'
    | '/diaries/$slug'
    | '/stories/$slug'
    | '/_authenticated/admin/about'
    | '/_authenticated/admin/collection'
    | '/_authenticated/admin/diary'
    | '/_authenticated/admin/gallery'
    | '/_authenticated/admin/shop'
    | '/_authenticated/admin/stories'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CollectionRoute: typeof CollectionRoute
  DiariesRoute: typeof DiariesRouteWithChildren
  GalleryRoute: typeof GalleryRoute
  ShopRoute: typeof ShopRoute
  StoriesRoute: typeof StoriesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diaries': {
      id: '/diaries'
      path: '/diaries'
      fullPath: '/diaries'
      preLoaderRoute: typeof DiariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof StoriesRoute
    }
    '/diaries/$slug': {
      id: '/diaries/$slug'
      path: '/$slug'
      fullPath: '/diaries/$slug'
      preLoaderRoute: typeof DiariesSlugRouteImport
      parentRoute: typeof DiariesRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/stories': {
      id: '/_authenticated/admin/stories'
      path: '/stories'
      fullPath: '/admin/stories'
      preLoaderRoute: typeof AuthenticatedAdminStoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/shop': {
      id: '/_authenticated/admin/shop'
      path: '/shop'
      fullPath: '/admin/shop'
      preLoaderRoute: typeof AuthenticatedAdminShopRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/gallery': {
      id: '/_authenticated/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AuthenticatedAdminGalleryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/diary': {
      id: '/_authenticated/admin/diary'
      path: '/diary'
      fullPath: '/admin/diary'
      preLoaderRoute: typeof AuthenticatedAdminDiaryRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/collection': {
      id: '/_authenticated/admin/collection'
      path: '/collection'
      fullPath: '/admin/collection'
      preLoaderRoute: typeof AuthenticatedAdminCollectionRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/about': {
      id: '/_authenticated/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AuthenticatedAdminAboutRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAboutRoute: typeof AuthenticatedAdminAboutRoute
  AuthenticatedAdminCollectionRoute: typeof AuthenticatedAdminCollectionRoute
  AuthenticatedAdminDiaryRoute: typeof AuthenticatedAdminDiaryRoute
  AuthenticatedAdminGalleryRoute: typeof AuthenticatedAdminGalleryRoute
  AuthenticatedAdminShopRoute: typeof AuthenticatedAdminShopRoute
  AuthenticatedAdminStoriesRoute: typeof AuthenticatedAdminStoriesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAboutRoute: AuthenticatedAdminAboutRoute,
    AuthenticatedAdminCollectionRoute: AuthenticatedAdminCollectionRoute,
    AuthenticatedAdminDiaryRoute: AuthenticatedAdminDiaryRoute,
    AuthenticatedAdminGalleryRoute: AuthenticatedAdminGalleryRoute,
    AuthenticatedAdminShopRoute: AuthenticatedAdminShopRoute,
    AuthenticatedAdminStoriesRoute: AuthenticatedAdminStoriesRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DiariesRouteChildren {
  DiariesSlugRoute: typeof DiariesSlugRoute
}

const DiariesRouteChildren: DiariesRouteChildren = {
  DiariesSlugRoute: DiariesSlugRoute,
}

const DiariesRouteWithChildren =
  DiariesRoute._addFileChildren(DiariesRouteChildren)

interface StoriesRouteChildren {
  StoriesSlugRoute: typeof StoriesSlugRoute
}

const StoriesRouteChildren: StoriesRouteChildren = {
  StoriesSlugRoute: StoriesSlugRoute,
}

const StoriesRouteWithChildren =
  StoriesRoute._addFileChildren(StoriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CollectionRoute: CollectionRoute,
  DiariesRoute: DiariesRouteWithChildren,
  GalleryRoute: GalleryRoute,
  ShopRoute: ShopRoute,
  StoriesRoute: StoriesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
